version: "3.9"
services:  
  app:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
  
  db:
    image: mongo:latest
    restart: always
    env_file:
     - .env
    ports:
      - '27017:27017'
  
